server.port: 7003

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db
  
logging:
  level:
    root: INFO
    de.mulenatic.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080
